[package]
name = "mhb-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.57"
anyhow = "1"
axum = "0.6.15"
chrono = "0.4.33"
serde = { version = "1.0", features = ["derive"] }
shuttle-axum = "0.14.0"
shuttle-runtime = "0.14.0"
shuttle-shared-db =  { version = "0.14.0", features = ["postgres"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "migrate"] }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }
serde_json = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }

