[package]
name = "mhb-server"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [".", "libs/*"]

[dependencies]
async-trait = "0.1.57"
anyhow = "1"
async-graphql = { version = "5.0.4", features = ["chrono"] }
async-graphql-axum = "5.0.4"
axum = "0.6.15"
mhb-boulder = { workspace = true } 
serde = { version = "1.0", features = ["derive"] }
shuttle-axum = "0.14.0"
shuttle-runtime = "0.14.0"
shuttle-shared-db =  { version = "0.14.0", features = ["postgres"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "migrate"] }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }

[dependencies.sea-orm]
version = "0.10.6"
features = ["runtime-tokio-native-tls", "sqlx-postgres", "debug-print"]

[dev-dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }
serde_json = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }

[workspace.dependencies]
mhb-boulder = { path = "libs/boulder" }
mhb-utils = { path = "libs/utils" }
