version: "3.1"

services:
    postgres:
        image: postgres
        container_name: mhb_postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgres/data
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}

volumes:
    postgres_data:
